#!/bin/bash
# Helper script to run Flutter commands with Firebase configuration from GitHub Secrets

# Build the Firebase dart-define flags
FIREBASE_FLAGS=""
if [[ -n "$FIREBASE_WEB_API_KEY" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_WEB_API_KEY=$FIREBASE_WEB_API_KEY"
fi
if [[ -n "$FIREBASE_WEB_APP_ID" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_WEB_APP_ID=$FIREBASE_WEB_APP_ID"
fi
if [[ -n "$FIREBASE_WEB_MEASUREMENT_ID" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_WEB_MEASUREMENT_ID=$FIREBASE_WEB_MEASUREMENT_ID"
fi
if [[ -n "$FIREBASE_ANDROID_API_KEY" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_ANDROID_API_KEY=$FIREBASE_ANDROID_API_KEY"
fi
if [[ -n "$FIREBASE_ANDROID_APP_ID" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_ANDROID_APP_ID=$FIREBASE_ANDROID_APP_ID"
fi
if [[ -n "$FIREBASE_IOS_API_KEY" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_IOS_API_KEY=$FIREBASE_IOS_API_KEY"
fi
if [[ -n "$FIREBASE_IOS_APP_ID" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_IOS_APP_ID=$FIREBASE_IOS_APP_ID"
fi
if [[ -n "$FIREBASE_IOS_BUNDLE_ID" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_IOS_BUNDLE_ID=$FIREBASE_IOS_BUNDLE_ID"
fi
if [[ -n "$FIREBASE_MACOS_API_KEY" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_MACOS_API_KEY=$FIREBASE_MACOS_API_KEY"
fi
if [[ -n "$FIREBASE_MACOS_APP_ID" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_MACOS_APP_ID=$FIREBASE_MACOS_APP_ID"
fi
if [[ -n "$FIREBASE_MACOS_BUNDLE_ID" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_MACOS_BUNDLE_ID=$FIREBASE_MACOS_BUNDLE_ID"
fi
if [[ -n "$FIREBASE_MESSAGING_SENDER_ID" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID"
fi
if [[ -n "$FIREBASE_PROJECT_ID" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID"
fi
if [[ -n "$FIREBASE_STORAGE_BUCKET" ]]; then
  FIREBASE_FLAGS="$FIREBASE_FLAGS --dart-define=FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET"
fi

# Run flutter with Firebase configuration and all passed arguments
exec flutter "$@" $FIREBASE_FLAGS