import 'package:flutter_test/flutter_test.dart';
import 'package:hand_foot_game_flutter/game/game_controller.dart';
import 'package:hand_foot_game_flutter/models/card.dart';

void main() {
  // Exact export from session_17841239000980098 (user paste).
  const export =
      'eyJ2IjozLCJzIjo5NjM2OTYsImciOnsicCI6MSwidCI6MSwiciI6MSwiYyI6MCwiZiI6ZmFsc2UsImQiOnRydWUsIm0iOmZhbHNlLCJxIjo2MH0sInBsYXllcnMiOlt7ImlkIjoiMSIsIm4iOiJZb3UiLCJ0IjowLCJzYyI6MTAwLCJwZCI6dHJ1ZSwiZnQiOmZhbHNlLCJtZWxkcyI6W3sidCI6MCwiYyI6WyIxMiwyIiwiMTIsMyIsIjEyLDIiXX0seyJ0IjowLCJjIjpbIjEwLDMiLCIxMCwwIiwiMTAsMSJdfSx7InQiOjAsImMiOlsiNywwIiwiNywyIiwiNywwIl19XSwiaCI6WyIzLDAiLCIzLDMiLCIzLDAiLCI0LDEiLCI0LDIiLCI3LDIiLCI3LDMiLCI4LDEiLCI4LDIiLCI5LDMiLCI5LDMiLCIxMSwyIiwiMTEsMCIsIjEyLDAiLCIxMiwyIiwiMCwzIiwiMSwyIiwiMSwxIl0sImYiOlsiNSwyIiwiMTEsMyIsIjksMSIsIjksMSIsIjUsMSIsIjIsMiIsIjAsMSIsIjYsMSIsIjEwLDIiLCI1LDIiLCIxMiwzIl0sInJzaCI6W119LHsiaWQiOiIyIiwibiI6IlN1ZSIsInQiOjEsInNjIjowLCJwZCI6dHJ1ZSwiZnQiOmZhbHNlLCJtZWxkcyI6W3sidCI6MSwiYyI6WyI1LDMiLCI1LDEiLCIxLDEiLCIxMywiLCI1LDMiXX0seyJ0IjoxLCJjIjpbIjExLDAiLCIxMSwzIiwiMTEsMCIsIjEsMSIsIjExLDMiXX0seyJ0IjowLCJjIjpbIjEwLDIiLCIxMCwwIiwiMTAsMiJdfSx7InQiOjAsImMiOlsiNCwyIiwiNCwxIiwiNCwwIiwiNCwzIl19LHsidCI6MCwiYyI6WyI4LDIiLCI4LDEiLCI4LDMiXX1dLCJoIjpbIjYsMiIsIjYsMyIsIjcsMSIsIjEyLDEiLCIwLDMiXSwiZiI6WyI0LDIiLCIxMywiLCIxMywiLCI0LDMiLCIxMSwyIiwiNCwzIiwiOSwzIiwiMCwzIiwiMywzIiwiNCwxIiwiMTAsMyJdLCJyc2giOltdfSx7ImlkIjoiMyIsIm4iOiJDbGFyYSIsInQiOjEsInNjIjowLCJwZCI6dHJ1ZSwiZnQiOnRydWUsIm1lbGRzIjpbeyJ0IjoxLCJjIjpbIjgsMSIsIjgsMyIsIjEsMCIsIjEzLCIsIjgsMCIsIjEsMyJdfSx7InQiOjEsImMiOlsiMTEsMSIsIjExLDEiLCIxLDAiLCIxMywiXX0seyJ0IjoxLCJjIjpbIjYsMCIsIjYsMyIsIjYsMSIsIjEzLCIsIjEsMyJdfSx7InQiOjAsImMiOlsiMCwyIiwiMCwwIiwiMCwwIl19LHsidCI6MSwiYyI6WyI1LDAiLCI1LDIiLCIxLDIiXX1dLCJoIjpbXSwiZiI6WyIzLDEiLCIzLDAiLCIzLDEiLCI1LDAiLCI2LDIiLCI3LDIiLCI5LDAiLCI5LDMiLCIxMCwzIiwiMTAsMiIsIjAsMSJdLCJyc2giOltdfV0sImRlY2siOnsic3oiOjkxLCJzIjo5NjM2OTYsInRvcCI6IjEwLDEifSwiZHAiOlsiNywwIiwiMiwxIiwiNCwwIiwiMiwxIiwiMiwwIiwiNywxIiwiNCwyIiwiMiwwIiwiOCwwIiwiMywyIiwiMiwzIiwiMywxIiwiMiwwIiwiMiwyIiwiOSwwIiwiOSwyIiwiNSwzIiwiOSwwIiwiMiwwIl0sInJhIjpbeyJtIjoi4o+t77iPIGNob3NlIG5vdCB0byBtZWxkIiwicCI6IkNsYXJhIiwidCI6MTc4NDEyNDExMzQ2Nn0seyJtIjoi8J+Xke+4jyBkaXNjYXJkZWQgMTAg4pmjIiwicCI6IkNsYXJhIiwidCI6MTc4NDEyNDExNjQ3OH0seyJtIjoi8J+RoCBwaWNrZWQgdXAgZm9vdCBwaWxlIiwicCI6IkNsYXJhIiwidCI6MTc4NDEyNDExNjQ3OH0seyJtIjoi8J+OryBkcmV3OiBLIOKZoywgNSDimaMiLCJwIjoiWW91IiwidCI6MTc4NDEyNDEyMDM3NH0seyJtIjoi8J+Xke+4jyBkaXNjYXJkZWQgNiDimaAiLCJwIjoiWW91IiwidCI6MTc4NDEyNDEyNzAwN30seyJtIjoi8J+OtCBkcmV3IDIgY2FyZHMgZnJvbSBkZWNrIiwicCI6IlN1ZSIsInQiOjE3ODQxMjQxMjc1MTV9LHsibSI6IvCfk4sgY3JlYXRlZCBuZXcgbWVsZDogOSDimaMsIDkg4pmmLCA5IOKZoCIsInAiOiJTdWUiLCJ0IjoxNzg0MTI0MTI5ODE5fSx7Im0iOiLij63vuI8gY2hvc2Ugbm90IHRvIG1lbGQiLCJwIjoiU3VlIiwidCI6MTc4NDEyNDEzMDYyM30seyJtIjoi8J+Xke+4jyBkaXNjYXJkZWQgMTAg4pmlIiwicCI6IlN1ZSIsInQiOjE3ODQxMjQxMzM2MjZ9LHsibSI6IvCfjrQgZHJldyAyIGNhcmRzIGZyb20gZGVjayIsInAiOiJDbGFyYSIsInQiOjE3ODQxMjQxMzcxMzN9LHsibSI6IuKelSBhZGRlZCAyIOKZoCB0byBleGlzdGluZyBtZWxkIiwicCI6IkNsYXJhIiwidCI6MTc4NDEyNDEzNzEzM30seyJtIjoi8J+Xke+4jyBkaXNjYXJkZWQgMyDimaUiLCJwIjoiQ2xhcmEiLCJ0IjoxNzg0MTI0MTM3MTMzfSx7Im0iOiJjb21wbGV0ZWQgdHVybiB3aXRoIGRpc2NhcmQiLCJwIjoiQ2xhcmEiLCJ0IjoxNzg0MTI0MTM3MTMzfSx7Im0iOiLwn46vIGRyZXc6IDEwIOKZoCwgMiDimaYiLCJwIjoiWW91IiwidCI6MTc4NDEyNDEzODE1OX1dLCJicCI6eyIyIjoiQm90UGVyc29uYWxpdHkuYWRhcHRpdmUiLCIzIjoiQm90UGVyc29uYWxpdHkuY29uc2VydmF0aXZlIn19';

  test(
    'session_17841239000980098: both mid-hand 8s are playable indices',
    () {
      final result = GameController.fromExportJson(export);
      expect(result, isNotNull);
      final gc = result!.controller;
      final human = gc.gameState.players.first;

      expect(human.currentHand[5].rank, CardRank.eight);
      expect(human.currentHand[6].rank, CardRank.eight);

      final indices = gc.getPlayableCardIndices(human);
      expect(indices.contains(5), isTrue, reason: 'first 8 (8♣) playable');
      expect(indices.contains(6), isTrue, reason: 'second 8 (8♠) playable');
    },
    tags: ['regression'],
  );
}
