// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: This is a STUB configuration for development.
/// Production configs are injected by Vercel builds or GitHub Actions from secrets.
/// For local testing, use the scripts/generate_firebase_config.sh script.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web; // Use web config for Windows
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  // STUB CONFIGURATIONS - Safe for public repository
  // Real configs are injected by GitHub Actions from secrets
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'stub-api-key',
    appId: '1:000000000000:web:stubappid',
    messagingSenderId: '000000000000',
    projectId: 'stub-project',
    authDomain: 'stub-project.firebaseapp.com',
    storageBucket: 'stub-project.appspot.com',
    measurementId: 'G-STUBMEASUREMENT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'stub-android-key',
    appId: '1:000000000000:android:stubandroidid',
    messagingSenderId: '000000000000',
    projectId: 'stub-project',
    storageBucket: 'stub-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'stub-ios-key',
    appId: '1:000000000000:ios:stubiosid',
    messagingSenderId: '000000000000',
    projectId: 'stub-project',
    storageBucket: 'stub-project.appspot.com',
    iosBundleId: 'com.example.handFootGameFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'stub-macos-key',
    appId: '1:000000000000:macos:stubmacosid',
    messagingSenderId: '000000000000',
    projectId: 'stub-project',
    storageBucket: 'stub-project.appspot.com',
    iosBundleId: 'com.example.handFootGameFlutter',
  );
}
