#!/bin/bash
# Bootstrap Firebase credentials for Cloud Agents from injected environment variables.
# Materializes FIREBASE_TOOLS_CREDENTIALS_JSON and FIREBASE_* vars to gitignored files.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_CREDS_FILE="$REPO_ROOT/.firebase/oauth-credentials.json"
CREDS_FILE="${FIREBASE_CREDENTIALS_FILE:-$DEFAULT_CREDS_FILE}"
MCP_STORE_DIR="$HOME/.config/configstore"
MCP_STORE="$MCP_STORE_DIR/firebase-tools.json"

REQUIRED_ENV_VARS=(
  FIREBASE_PROJECT_ID
  FIREBASE_TOOLS_CREDENTIALS_JSON
  FIREBASE_WEB_API_KEY
  FIREBASE_WEB_APP_ID
)

OPTIONAL_ENV_VARS=(
  FIREBASE_PROJECT_NUMBER
  FIREBASE_AUTH_EMAIL
  FIREBASE_MESSAGING_SENDER_ID
  FIREBASE_STORAGE_BUCKET
  FIREBASE_WEB_MEASUREMENT_ID
  FIREBASE_ANDROID_API_KEY
  FIREBASE_ANDROID_APP_ID
  FIREBASE_IOS_API_KEY
  FIREBASE_IOS_APP_ID
  FIREBASE_IOS_BUNDLE_ID
  FIREBASE_MACOS_API_KEY
  FIREBASE_MACOS_APP_ID
  FIREBASE_MACOS_BUNDLE_ID
  FIREBASE_OAUTH_CLIENT_SECRET
)

SERVICE_ACCOUNT_FILE="$REPO_ROOT/.firebase/hand-foot-flutter-firebase.json"
LEGACY_SERVICE_ACCOUNT_FILE="$REPO_ROOT/.firebase/hand-foot-service-account.json"

missing=()
for var in "${REQUIRED_ENV_VARS[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    missing+=("$var")
  fi
done

if [[ ${#missing[@]} -gt 0 ]]; then
  echo "❌ Missing required Firebase environment variables:"
  for var in "${missing[@]}"; do
    echo "   - $var"
  done
  echo ""
  echo "Present FIREBASE_* variables:"
  env | grep '^FIREBASE_' | cut -d= -f1 | sort || true
  echo ""
  echo "Run ./scripts/check_firebase_credentials.sh for a full status report."
  exit 1
fi

mkdir -p "$REPO_ROOT/.firebase"
mkdir -p "$MCP_STORE_DIR"
umask 077

# Write OAuth credentials (never echo contents)
install -m 600 /dev/null "$CREDS_FILE"
printf '%s' "$FIREBASE_TOOLS_CREDENTIALS_JSON" > "$CREDS_FILE"
chmod 600 "$CREDS_FILE"
install -m 600 /dev/null "$MCP_STORE"
cp "$CREDS_FILE" "$MCP_STORE"
chmod 600 "$MCP_STORE"

echo "✅ Wrote OAuth credentials"
echo "   Workspace: $CREDS_FILE"
echo "   MCP store: $MCP_STORE"

# Generate .env from injected FIREBASE_* variables
ENV_FILE="$REPO_ROOT/.env"
install -m 600 /dev/null "$ENV_FILE"
{
  echo "# AUTO-GENERATED by scripts/bootstrap_firebase_agent_env.sh"
  echo "# DO NOT COMMIT — .env is gitignored"
  echo ""
  for var in "${REQUIRED_ENV_VARS[@]}" "${OPTIONAL_ENV_VARS[@]}" FIREBASE_CREDENTIALS_FILE; do
    if [[ -n "${!var:-}" ]]; then
      # Skip writing the large JSON blob into .env
      if [[ "$var" == "FIREBASE_TOOLS_CREDENTIALS_JSON" ]]; then
        continue
      fi
      printf '%s=%s\n' "$var" "${!var}"
    fi
  done
  printf 'FIREBASE_CREDENTIALS_FILE=%s\n' "$CREDS_FILE"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo "✅ Generated $ENV_FILE"

if [[ -n "${FIREBASE_HAND_FOOT_SERVICE_ACCOUNT_B64:-}" ]]; then
  install -m 600 /dev/null "$SERVICE_ACCOUNT_FILE"
  python3 - "$SERVICE_ACCOUNT_FILE" <<'PY'
import base64
import json
import os
import sys

out_path = sys.argv[1]
os.chmod(out_path, 0o600)
raw = base64.b64decode(os.environ["FIREBASE_HAND_FOOT_SERVICE_ACCOUNT_B64"]).decode("utf-8")
data = json.loads(raw)
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
os.chmod(out_path, 0o600)
PY
  echo "✅ Wrote service account file: $SERVICE_ACCOUNT_FILE"
elif [[ -f "$SERVICE_ACCOUNT_FILE" ]]; then
  echo "✅ Using existing service account file: $SERVICE_ACCOUNT_FILE"
elif [[ -f "$LEGACY_SERVICE_ACCOUNT_FILE" ]]; then
  echo "✅ Using legacy service account file: $LEGACY_SERVICE_ACCOUNT_FILE"
  SERVICE_ACCOUNT_FILE="$LEGACY_SERVICE_ACCOUNT_FILE"
fi

# Non-secret agent metadata for fast discovery
AGENT_CONFIG="$REPO_ROOT/.firebase/agent-config.json"
install -m 600 /dev/null "$AGENT_CONFIG"
python3 - "$AGENT_CONFIG" "$CREDS_FILE" "$ENV_FILE" "$MCP_STORE" "$SERVICE_ACCOUNT_FILE" <<'PY'
import json
import os
import sys
from datetime import datetime, timezone

out_path, creds_file, env_file, mcp_store, service_account_file = sys.argv[1:6]
config = {
    "bootstrappedAt": datetime.now(timezone.utc).isoformat(),
    "projectId": os.environ.get("FIREBASE_PROJECT_ID"),
    "authEmail": os.environ.get("FIREBASE_AUTH_EMAIL"),
    "paths": {
        "credentialsFile": creds_file,
        "envFile": env_file,
        "mcpStore": mcp_store,
        "serviceAccountFile": service_account_file,
    },
    "cloudAgentSecretsInjected": bool(os.environ.get("CLOUD_AGENT_INJECTED_SECRET_NAMES")),
    "hasOAuthClientSecret": bool(os.environ.get("FIREBASE_OAUTH_CLIENT_SECRET")),
    "hasServiceAccountB64": bool(os.environ.get("FIREBASE_HAND_FOOT_SERVICE_ACCOUNT_B64")),
    "preferredAnalyticsAuth": "service-account" if os.environ.get("FIREBASE_HAND_FOOT_SERVICE_ACCOUNT_B64") or os.path.exists(service_account_file) else "oauth-user",
    "quickstartDoc": "docs/firebase_mcp_quickstart.md",
}
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(config, f, indent=2)
    f.write("\n")
PY
echo "✅ Wrote $AGENT_CONFIG"

# Sync workspace copy via existing refresh script when MCP store is source of truth
if [[ -x "$REPO_ROOT/scripts/refresh_firebase_agent_credentials.sh" ]]; then
  FIREBASE_TOOLS_CONFIG="$MCP_STORE" "$REPO_ROOT/scripts/refresh_firebase_agent_credentials.sh" || true
fi

echo ""
echo "Bootstrap complete."
echo "  Project: ${FIREBASE_PROJECT_ID}"
echo "  Account: ${FIREBASE_AUTH_EMAIL:-unknown}"
echo ""
echo "Next steps:"
echo "  1. Firebase MCP: firebase_update_environment with project_dir=$REPO_ROOT active_project=${FIREBASE_PROJECT_ID}"
echo "  2. Verify: firebase_get_environment"
echo "  3. Query: node scripts/query_analytics_session.js --recent --turn-summaries --decision-outcomes"
if [[ -f "$SERVICE_ACCOUNT_FILE" || -n "${FIREBASE_HAND_FOOT_SERVICE_ACCOUNT_B64:-}" ]]; then
  echo "  Analytics auth: service-account (preferred)"
fi
