#!/usr/bin/env bash
# Generate lib/firebase_options.dart from FIREBASE_* environment variables.
# Used by Vercel builds and local setup (scripts/setup_local_firebase.sh).
# Never commit the generated file with real credentials.
set -euo pipefail

OUTPUT_FILE="${1:-lib/firebase_options.dart}"

if [ -z "${FIREBASE_PROJECT_ID:-}" ] || [ -z "${FIREBASE_WEB_API_KEY:-}" ] || [ -z "${FIREBASE_WEB_APP_ID:-}" ]; then
  echo "Error: Missing required Firebase env vars: FIREBASE_PROJECT_ID, FIREBASE_WEB_API_KEY, FIREBASE_WEB_APP_ID"
  exit 1
fi

: "${FIREBASE_MESSAGING_SENDER_ID:?FIREBASE_MESSAGING_SENDER_ID is required}"
: "${FIREBASE_STORAGE_BUCKET:?FIREBASE_STORAGE_BUCKET is required}"

cat > "$OUTPUT_FILE" << EOF
// AUTO-GENERATED at build time — DO NOT COMMIT WITH REAL VALUES
// Generated by scripts/generate_firebase_options_from_env.sh

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '${FIREBASE_WEB_API_KEY}',
    appId: '${FIREBASE_WEB_APP_ID}',
    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
    projectId: '${FIREBASE_PROJECT_ID}',
    authDomain: '${FIREBASE_PROJECT_ID}.firebaseapp.com',
    storageBucket: '${FIREBASE_STORAGE_BUCKET}',
    measurementId: '${FIREBASE_WEB_MEASUREMENT_ID:-}',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '${FIREBASE_ANDROID_API_KEY:-stub-android-key}',
    appId: '${FIREBASE_ANDROID_APP_ID:-1:000000000000:android:stub}',
    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
    projectId: '${FIREBASE_PROJECT_ID}',
    storageBucket: '${FIREBASE_STORAGE_BUCKET}',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '${FIREBASE_IOS_API_KEY:-stub-ios-key}',
    appId: '${FIREBASE_IOS_APP_ID:-1:000000000000:ios:stub}',
    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
    projectId: '${FIREBASE_PROJECT_ID}',
    storageBucket: '${FIREBASE_STORAGE_BUCKET}',
    iosBundleId: '${FIREBASE_IOS_BUNDLE_ID:-com.example.app}',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '${FIREBASE_MACOS_API_KEY:-stub-macos-key}',
    appId: '${FIREBASE_MACOS_APP_ID:-1:000000000000:macos:stub}',
    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
    projectId: '${FIREBASE_PROJECT_ID}',
    storageBucket: '${FIREBASE_STORAGE_BUCKET}',
    iosBundleId: '${FIREBASE_MACOS_BUNDLE_ID:-com.example.app}',
  );
}
EOF

if ! grep -q "class DefaultFirebaseOptions" "$OUTPUT_FILE"; then
  echo "Error: Generated Firebase config is invalid"
  exit 1
fi

echo "Generated $OUTPUT_FILE from FIREBASE_* environment variables"
